version: "1"

services:
  reactapp:
    build:
      context: ../frontend
    restart: always
    container_name: reactApp
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
